whitelist_rules:
- anyobject_protocol
- array_init
- closing_brace
- closure_end_indentation
- closure_spacing
- closure_body_length
- collection_alignment
- colon
- comma
- compiler_protocol_init
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- explicit_init
- implicit_return
- joined_default_parameter
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- duplicate_enum_cases
- duplicate_imports
- empty_count
- legacy_constructor
- legacy_multiple
- legacy_nsgeometry_functions
- multiline_function_chains
- multiline_literal_brackets
- legacy_random
- literal_expression_end_indentation
- let_var_whitespace
- multiline_arguments
- mark
- opening_brace
- last_where
- operator_usage_whitespace
- private_over_fileprivate
- protocol_property_accessors_order
- redundant_discardable_let
- redundant_nil_coalescing
- redundant_objc_attribute
- redundant_optional_initialization
- redundant_void_return
- return_arrow_whitespace
- pattern_matching_keywords
- statement_position
- trailing_comma
- trailing_newline
- trailing_semicolon
- trailing_whitespace
- deployment_target
- reduce_boolean
- reduce_into
- unneeded_parentheses_in_closure_argument
- unused_closure_parameter
- unowned_variable_capture
- vertical_whitespace
- void_return
- fatal_error_message
- unused_capture_list
- modifier_order
- multiline_parameters
- multiline_parameters_brackets
- overridden_super_call
- prohibited_super_call
- vertical_parameter_alignment_on_call
- yoda_condition
- class_delegate_protocol
- closure_parameter_position
- contains_over_first_not_nil
- control_statement
- discarded_notification_center_observer
- discouraged_direct_init
- dynamic_inline
- empty_string
- first_where
- nimble_operator
- for_where
- force_try
- generic_type_name
- implicit_getter
- operator_whitespace
- identical_operands
- redundant_set_access_control
- redundant_string_enum_value
- shorthand_operator
- sorted_first_last
- superfluous_disable_command
- switch_case_alignment
- switch_case_on_newline
- syntactic_sugar
- unneeded_break_in_switch
- inert_defer
- is_disjoint
- unused_enumerated
- unused_optional_binding
- unused_import
- unused_private_declaration
- unused_setter_value
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_whitespace_opening_braces
- vertical_whitespace_closing_braces
- weak_delegate
